
- name: Roles config
  hosts: all
  become: true
  vars:
    universal_pass: "d3f@u1t_p@ssw0rd"
  roles:
    - baseconfig
    - docker 
    - packmate
    - s4dfarm
    - codeserver
    - firegex
    - post-install