---
# tasks file for baseconfig

- name: Update repositories and install debian software
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - vim 
    - htop 
    - tmux
    - curl 
    - wget 
    - openvpn
    - wireguard 
    - resolvconf
    - tcpdump
    - pktstat
